name: auto-format
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format

    - name: Format with clang-format
      run: find . -type f \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-format -i

    - name: Push format results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}

        git config --global user.name "GitHub"
        git config --global user.email "noreply@github.com"
        git add .

        if (git diff --cached --shortstat | grep '[0-9]'); then
          git commit -m "[auto-formatter] format commit ${GITHUB_SHA}"
          git push origin HEAD:${GITHUB_REF}
        else
          echo "No updated timestamps."
        fi
