name: format
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format

    - name: Apply formatter
      run: clang-format --dry-run --Werror $(find . -name "*.cpp" -or -name "*.hpp")
