name: verify
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/format.yml
    secrets: inherit

  test:
    needs: format
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  finalize:
    needs: test
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit
